# Generated by Django 5.2.9 on 2026-01-14 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_appointmentschedule'),
        ('patient', '0004_chatmessage_image_alter_chatmessage_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(help_text='Diagnosis / clinical notes')),
                ('medications', models.TextField(help_text='Medicines with dosage and duration')),
                ('advice', models.TextField(blank=True, help_text='Lifestyle advice / follow-up instructions', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='patient.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='doctor.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patient.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
