# Generated by Django 4.2.7 on 2026-01-26 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_appointmentchatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentchatmessage',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_messages', to='patient.appointment'),
        ),
        migrations.AlterModelTable(
            name='appointmentchatmessage',
            table='patient_appointmentchatmessage',
        ),
    ]
