# Generated by Django 4.2.7 on 2026-03-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_hospital_approval_status_hospital_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
