# Generated by Django 4.2.7 on 2026-03-27 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_appointmentschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid Indian mobile number (10 digits starting with 6-9).', regex='^[6-9][0-9]{9}$')]),
        ),
    ]
