# Generated by Django 4.2.7 on 2026-03-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_doctor_approval_status_doctor_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
